-- =============================================================================
-- cortex: Canonical DB Schema Additions (6 Epics)
-- =============================================================================
--
-- Purpose
--   This file is the single source of truth for every new table, column, and
--   index introduced across the six concurrent epics landing on top of the
--   v0.20.x schema in `src/db/pool.rs`. Implementers wire these statements
--   into per-epic migrations (assigning their own `schema_migrations` version
--   numbers) but MUST NOT diverge from the shapes, constraints, or index
--   definitions captured here.
--
-- Source specs (paths relative to repo root)
--   - docs/superpowers/specs/2026-05-16-agent-mode-design.md            (Epic A: cortex-qgnx)
--   - docs/superpowers/specs/2026-05-16-enrichment-framework-design.md  (Epic B: cortex-1wjr)
--   - docs/superpowers/specs/2026-05-16-api-pollers-design.md           (Epic C: cortex-awvr)
--   - docs/superpowers/specs/2026-05-16-probe-registry-design.md        (Epic D: cortex-fue9)
--   - docs/superpowers/specs/2026-05-16-digest-notifications-design.md  (Epic E: cortex-h6dg)
--   - docs/superpowers/specs/2026-05-16-rag-incidents-design.md         (Epic F: cortex-h6da)
--
-- Ordering rules
--   - Statements are arranged so the file executes top-to-bottom against a
--     fresh `logs` table without forward references.
--   - `ALTER TABLE logs ADD COLUMN` statements live at the top of Epic B's
--     section because the partial indexes there (and rule-evaluation queries
--     in Epic E) depend on those columns.
--   - Each subsequent epic's `CREATE TABLE` and `CREATE INDEX` statements are
--     self-contained: they reference no other epic's new objects.
--
-- Style
--   - Mirrors the conventions in `src/db/pool.rs`:
--       * `CREATE TABLE IF NOT EXISTS` / `CREATE INDEX IF NOT EXISTS`
--       * TEXT-typed RFC 3339 timestamps with
--         `DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))` where applicable
--       * `INTEGER` for unix-epoch-millis where the spec is explicit (some
--         epics — D, E, F — prefer integer epochs over RFC 3339 strings)
--       * Partial indexes (`WHERE col IS NOT NULL`) match the migration-8
--         pattern for AI-metadata columns
--       * No `schema_migrations` INSERTs here — implementers add those when
--         they slot these statements into versioned migrations in pool.rs.
--
-- CONTRACT
--   Changing any statement in this file requires a corresponding update to
--   the source spec listed in that section's banner. Do NOT edit the SQL to
--   match drifted code, and do NOT edit a spec without also updating this
--   file. Implementers MAY add `INSERT INTO schema_migrations (version)
--   VALUES (N);` lines when wiring these into `pool.rs`; everything else in
--   this file is normative.
-- =============================================================================


-- ====== Epic A: Agent Mode — WebSocket + JSON-RPC 2.0 (cortex-qgnx) ======
-- Source: docs/superpowers/specs/2026-05-16-agent-mode-design.md
--   §9 (`agents` table + indices)
-- NOTE: spec A §16 open-question #4 originally pre-created a `host_metrics`
-- table for Epic D's writer. Resolved (bead cortex-swv9): the table is
-- removed from Epic A entirely; Epic D's `metrics_gauge` is the canonical
-- target for both probe results AND any future `metrics.push` payloads.
-- V1 still drops incoming `metrics.push` on the floor.

-- Per-host agent identity, token state, and connection lifecycle.
-- (Source: §9 — "agents Table")
CREATE TABLE IF NOT EXISTS agents (
    host_id                 TEXT PRIMARY KEY,            -- UUID v4 generated by agent on first run
    hostname                TEXT NOT NULL,               -- last-known; not unique (hostnames may change)
    agent_version           TEXT,                        -- semver reported on last hello
    platform_json           TEXT,                        -- serialised PlatformInfo
    capabilities_json       TEXT,                        -- serialised Capabilities (incl. supported_probes)

    token_hash              BLOB,                        -- BLAKE3(token); NULL when revoked
    token_hash_prev         BLOB,                        -- previous hash during rotation grace window
    token_rotated_at        TEXT,                        -- RFC 3339; set on rotate

    connection_state        TEXT NOT NULL                -- 'NeverConnected'|'Active'|'Disconnected'|'Revoked'
                            DEFAULT 'NeverConnected',
    session_id              TEXT,                        -- current session UUID (Active only)
    accepted_seq            INTEGER NOT NULL DEFAULT 0,  -- high-water mark of acked logs.push seq

    first_seen              TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
    last_handshake          TEXT,                        -- updated on every accepted agent.hello
    last_seen               TEXT,                        -- updated on heartbeat / logs.push
    last_disconnect         TEXT,                        -- updated on WS close
    last_disconnect_reason  TEXT                         -- "<close_code> <msg>"
);

-- Lookup by human-readable hostname (admin CLI, status panes). (Source: §9)
CREATE INDEX IF NOT EXISTS idx_agents_hostname ON agents(hostname);

-- "Show me all Active agents" / fleet roll-ups. (Source: §9)
CREATE INDEX IF NOT EXISTS idx_agents_state ON agents(connection_state);

-- Sort agents by recency for dashboards / silent-host detection. (Source: §9)
CREATE INDEX IF NOT EXISTS idx_agents_lastseen ON agents(last_seen);

-- (host_metrics table removed per bead cortex-swv9 — see header note above.
-- Epic D's metrics_gauge replaces it. If a future Epic A v2 wires the agent's
-- metrics.push path to a writer, it lands rows in metrics_gauge directly.)


-- ====== Epic B: Enrichment / Parser Framework (cortex-1wjr) ==============
-- Source: docs/superpowers/specs/2026-05-16-enrichment-framework-design.md
--   §5 (indexed-column migration: http_status, auth_outcome, dns_blocked, event_action)
--   §6 (parse_error column — no index)

-- Structured field extracted by the swag/nginx parser (3-digit HTTP code).
-- (Source: §5, §7.4)
ALTER TABLE logs ADD COLUMN http_status INTEGER;

-- Structured field extracted by the authelia parser:
--   'success' | 'failure' | 'denied' | 'challenge'
-- (Source: §5, §7.3)
ALTER TABLE logs ADD COLUMN auth_outcome TEXT;

-- Structured field extracted by the adguard parser. 0/1 (boolean as int);
-- NULL when not applicable (e.g. rewrites — see §13 open-question #3).
-- (Source: §5, §7.5)
ALTER TABLE logs ADD COLUMN dns_blocked INTEGER;

-- Structured field extracted by kernel/docker_event/swag/fail2ban parsers.
-- Closed enum per source (oom_kill, link_up, die, http_request, ban, ...).
-- (Source: §5, §7.1/§7.2/§7.4/§7.6)
ALTER TABLE logs ADD COLUMN event_action TEXT;

-- Per-row parser diagnostic: "{parser_name}: {ParserError::Display}", truncated
-- to 512 bytes. No index — diagnostic-only, not a filter dimension.
-- (Source: §6 — parse-error storage decision)
ALTER TABLE logs ADD COLUMN parse_error TEXT;

-- Partial indexes mirror the migration-8 AI-metadata pattern: only non-NULL
-- rows index, keeping size proportional to recognised traffic. (Source: §5)

-- "All 5xx upstreams from SWAG in the last hour." (Source: §5)
CREATE INDEX IF NOT EXISTS idx_logs_http_status_time
    ON logs(http_status, timestamp)
    WHERE http_status IS NOT NULL;

-- "All failed MFA attempts today." (Source: §5)
CREATE INDEX IF NOT EXISTS idx_logs_auth_outcome_time
    ON logs(auth_outcome, timestamp)
    WHERE auth_outcome IS NOT NULL;

-- "All DNS blocks for client X." (Source: §5)
CREATE INDEX IF NOT EXISTS idx_logs_dns_blocked_time
    ON logs(dns_blocked, timestamp)
    WHERE dns_blocked IS NOT NULL;

-- "All container die / oom_kill events last week." (Source: §5)
CREATE INDEX IF NOT EXISTS idx_logs_event_action_time
    ON logs(event_action, timestamp)
    WHERE event_action IS NOT NULL;


-- ====== Epic C: API Pollers — UniFi + AdGuard (cortex-awvr) ==============
-- Source: docs/superpowers/specs/2026-05-16-api-pollers-design.md
--   §4 (poller_checkpoints schema — UniFi events + alarms)
--   §5 (AdGuard query-log cursor)

-- One row per (poller, instance) cursor. Pollers update on every successful
-- emit; cursors do NOT advance on failure (idempotency invariant — §6).
-- (Source: §4 — UniFi cursor strategy; §5 — AdGuard cursor strategy)
CREATE TABLE IF NOT EXISTS poller_checkpoints (
    poller        TEXT NOT NULL,   -- 'unifi-events' | 'unifi-alarms' | 'adguard-querylog'
    instance      TEXT NOT NULL,   -- controller/site identifier; '' for default
    cursor_a      TEXT,            -- primary cursor (time ms for UniFi / rfc3339 for AdGuard)
    cursor_b      TEXT,            -- secondary cursor (mongo _id for UniFi; unused for AdGuard)
    last_tick_at  TEXT,            -- RFC 3339 timestamp of the most recent tick
    last_error    TEXT,            -- last tick's error string (NULL on success)
    PRIMARY KEY (poller, instance)
);


-- ====== Epic D: Probe Registry + Live-state MCP Actions (cortex-fue9) ====
-- Source: docs/superpowers/specs/2026-05-16-probe-registry-design.md
--   §6 (metrics_gauge — coarse time-series for operational triage)
--   §7 (probe_results — structured JSON payloads)

-- Numeric scalar gauges emitted by probes (disk.usage, mem.pressure). One row
-- per scalar sample. Retention/downsampling handled by db::maintenance.
-- NOTE: distinct from Epic A's `host_metrics` — that table buffers raw
-- `metrics.push` payloads from the agent wire protocol; this table is the
-- structured store written by the probe execution path. (Source: §6)
CREATE TABLE IF NOT EXISTS metrics_gauge (
    id           INTEGER PRIMARY KEY AUTOINCREMENT,
    host_id      TEXT NOT NULL,
    metric_name  TEXT NOT NULL,                  -- e.g. "mem.used_pct"
    labels       TEXT NOT NULL DEFAULT '{}',     -- JSON, sorted keys for dedup
    value        REAL NOT NULL,
    ts           INTEGER NOT NULL                -- unix epoch millis
);

-- "Latest mem.used_pct for dookie" / per-host time slice. (Source: §6)
CREATE INDEX IF NOT EXISTS idx_metrics_host_metric_ts
    ON metrics_gauge(host_id, metric_name, ts DESC);

-- "All disk.used_pct across the fleet, recent first." (Source: §6)
CREATE INDEX IF NOT EXISTS idx_metrics_metric_ts
    ON metrics_gauge(metric_name, ts DESC);

-- Pure-time retention sweeps. (Source: §6)
CREATE INDEX IF NOT EXISTS idx_metrics_ts
    ON metrics_gauge(ts);

-- ====== Epic D rollups: metrics_gauge_5m / metrics_gauge_1h ======
-- Cited by retention-policy.md and probe-registry-design.md §6.
-- Retention: 5m → 90d, 1h → 365d. Downsampling worker is part of Epic D maintenance.

CREATE TABLE IF NOT EXISTS metrics_gauge_5m (
    host_id      TEXT NOT NULL,
    metric_name  TEXT NOT NULL,
    labels_hash  TEXT NOT NULL,            -- BLAKE3 of normalized labels JSON; reduces label cardinality
    labels       TEXT,                     -- full labels JSON (denormalized for query convenience)
    bucket_ts    INTEGER NOT NULL,         -- 5-minute bucket start, unix epoch millis aligned to 300_000ms
    value_avg    REAL NOT NULL,
    value_min    REAL NOT NULL,
    value_max    REAL NOT NULL,
    value_count  INTEGER NOT NULL,         -- sample count in bucket; >0 invariant
    PRIMARY KEY (host_id, metric_name, labels_hash, bucket_ts)
) WITHOUT ROWID;

CREATE INDEX IF NOT EXISTS idx_metrics_gauge_5m_lookup
    ON metrics_gauge_5m (host_id, metric_name, bucket_ts DESC);

CREATE TABLE IF NOT EXISTS metrics_gauge_1h (
    host_id      TEXT NOT NULL,
    metric_name  TEXT NOT NULL,
    labels_hash  TEXT NOT NULL,
    labels       TEXT,
    bucket_ts    INTEGER NOT NULL,         -- 1-hour bucket start, aligned to 3_600_000ms
    value_avg    REAL NOT NULL,
    value_min    REAL NOT NULL,
    value_max    REAL NOT NULL,
    value_count  INTEGER NOT NULL,
    PRIMARY KEY (host_id, metric_name, labels_hash, bucket_ts)
) WITHOUT ROWID;

CREATE INDEX IF NOT EXISTS idx_metrics_gauge_1h_lookup
    ON metrics_gauge_1h (host_id, metric_name, bucket_ts DESC);

-- One row per probe execution. JSON payload is a serialized ProbeOutput.
-- Eviction: keep last 200 per (host_id, probe_name); hard ceiling 30 days.
-- (Source: §7)
CREATE TABLE IF NOT EXISTS probe_results (
    id            INTEGER PRIMARY KEY AUTOINCREMENT,
    host_id       TEXT NOT NULL,
    probe_name    TEXT NOT NULL,
    requested_by  TEXT,                          -- 'schedule' | 'mcp:<client>' | 'rpc'
    request_ts    INTEGER NOT NULL,              -- unix ms
    response_ts   INTEGER NOT NULL,              -- unix ms; == request_ts on error
    duration_ms   INTEGER NOT NULL,
    payload       TEXT NOT NULL,                 -- JSON ProbeOutput; '{}' on error
    status        TEXT NOT NULL,                 -- 'ok' | 'timeout' | 'unsupported' | 'error'
    error         TEXT                           -- populated when status != 'ok'
);

-- "Latest result for probe X on host Y" via index seek + LIMIT 1. (Source: §7)
CREATE INDEX IF NOT EXISTS idx_probe_results_host_probe_ts
    ON probe_results(host_id, probe_name, response_ts DESC);

-- "All recent failed probes" for status panes. (Source: §7)
CREATE INDEX IF NOT EXISTS idx_probe_results_status
    ON probe_results(status, response_ts DESC);


-- ====== Epic E: Digest + Push Notifications (cortex-h6dg) ================
-- Source: docs/superpowers/specs/2026-05-16-digest-notifications-design.md
--   §6 (alert_state table — dedup, cooldown, fingerprinting)

-- One row per (rule, fingerprint) describing the current alert lifecycle.
-- Fingerprint = stable hash of the rule's group_by-projected fields.
-- (Source: §6 — State Store)
CREATE TABLE IF NOT EXISTS alert_state (
    rule_id         TEXT    NOT NULL,
    fingerprint     TEXT    NOT NULL,
    first_fired_at  INTEGER NOT NULL,            -- unix ms
    last_fired_at   INTEGER NOT NULL,            -- unix ms
    fire_count      INTEGER NOT NULL DEFAULT 1,
    last_log_id     INTEGER,                     -- references logs.id of the triggering row
    severity        TEXT    NOT NULL,            -- 'info' | 'warn' | 'critical'
    ack_at          INTEGER,                     -- NULL while active; unix ms when acked
    ack_by          TEXT,                        -- 'auto' | 'mcp:<user>' | 'timeout' | 'quiet_hours'
    snooze_until    INTEGER,                     -- NULL or unix ms
    PRIMARY KEY (rule_id, fingerprint)
);

-- "All currently active alerts" — partial index over the active set only.
-- (Source: §6)
CREATE INDEX IF NOT EXISTS idx_alert_state_active
    ON alert_state(ack_at)
    WHERE ack_at IS NULL;

-- "Recent fire history for rule X" / escalator scans. (Source: §6)
CREATE INDEX IF NOT EXISTS idx_alert_state_rule_lastfired
    ON alert_state(rule_id, last_fired_at);


-- ====== Epic F: RAG over Historical Incidents (cortex-h6da) ==============
-- Source: docs/superpowers/specs/2026-05-16-rag-incidents-design.md
--   §6 (incidents table — host/xhost signatures, embed lifecycle, resolution link)

-- One row per closed incident: trigger event + coalesced window + structured
-- fields. Source of truth for the RAG corpus; Qdrant is derived. UUIDv7 PK
-- keeps natural time ordering. (Source: §6 — Storage)
CREATE TABLE IF NOT EXISTS incidents (
    incident_id            TEXT PRIMARY KEY,            -- UUIDv7
    signature_hash         TEXT NOT NULL,               -- host-scoped fingerprint
    signature_hash_xhost   TEXT NOT NULL,               -- host-stripped fingerprint
    hostname               TEXT NOT NULL,
    app_name               TEXT NOT NULL,
    source                 TEXT NOT NULL,               -- 'kernel.oom' | 'docker_event' | 'fail2ban' | ...
    severity               TEXT,
    first_seen             TEXT NOT NULL,               -- ISO 8601 (RFC 3339)
    last_seen              TEXT NOT NULL,               -- ISO 8601 (RFC 3339)
    event_count            INTEGER NOT NULL,
    sample_log_ids         TEXT NOT NULL,               -- JSON array of logs.id values
    structured_fields      TEXT NOT NULL,               -- JSON, source-shaped
    card_path              TEXT,                        -- /data/incidents/<id>.md (axon staging)
    embed_status           TEXT NOT NULL DEFAULT 'pending',  -- 'pending' | 'embedded' | 'failed'
    embed_job_id           TEXT,                        -- axon job id (most recent embed call)
    embed_attempts         INTEGER NOT NULL DEFAULT 0,
    resolution_session_id  TEXT,                        -- mnemo session that resolved this incident
    resolution_notes       TEXT,                        -- freeform, from mark_incident_resolved
    closed                 INTEGER NOT NULL DEFAULT 0   -- 0/1; 1 once finalized and embedded
);

-- "Have we seen this signature anywhere recently?" cross-host queries.
-- (Source: §6)
CREATE INDEX IF NOT EXISTS idx_incidents_sig_xhost
    ON incidents(signature_hash_xhost, last_seen DESC);

-- "Show me incidents on jenny in the last 24h" — host timeline. (Source: §6)
CREATE INDEX IF NOT EXISTS idx_incidents_host_time
    ON incidents(hostname, last_seen DESC);

-- Embed-pipeline worker scans only the non-embedded set. Partial index keeps
-- this trivially fast even as the corpus grows. (Source: §6)
CREATE INDEX IF NOT EXISTS idx_incidents_embed_status
    ON incidents(embed_status)
    WHERE embed_status != 'embedded';

-- =============================================================================
-- End of contract.
-- =============================================================================
