mod correlate;
mod error;
pub(crate) mod error_detection;
mod models;
mod service;
pub(crate) mod time;

pub use correlate::severity_at_or_above;
pub use error::{ServiceError, ServiceResult};
pub use models::{
    AbuseIncident,
    AbuseMatch,
    AbuseSearchRequest,
    AbuseSearchResponse,
    AppLogCount,
    AskHistoryRequest,
    AskHistoryResponse,
    // Error detection
    AckErrorRequest,
    AckErrorResponse,
    AiCheckpointsRequest,
    AiCorrelateRequest,
    AiCorrelateResponse,
    AiCorrelationAnchor,
    AiIncidentRequest,
    AiIncidentResponse,
    AiInvestigateRequest,
    AiInvestigateResponse,
    AiParseErrorsRequest,
    AiProjectEntry,
    AiPruneCheckpointsRequest,
    AiSessionEntry,
    AiToolEntry,
    AnomaliesRequest,
    AnomaliesResponse,
    ClockSkewRequest,
    ClockSkewResponse,
    CompareRequest,
    CompareResponse,
    ContextRequest,
    ContextResponse,
    CorrelateEventsRequest,
    CorrelateEventsResponse,
    CorrelatedHost,
    DbBackupResult,
    DbCheckpointRequest,
    DbCheckpointResult,
    DbIntegrityRequest,
    DbIntegrityResult,
    DbMaintenanceStatus,
    DbStats,
    DbVacuumRequest,
    DbVacuumResult,
    ErrorSignatureEntry,
    ErrorSummaryEntry,
    GetErrorsRequest,
    GetErrorsResponse,
    GetLogRequest,
    GetLogResponse,
    HostEntry,
    CorrelatedSession,
    IncidentCluster,
    IncidentContextRequest,
    IncidentContextResponse,
    IncidentEvent,
    IncidentEvidence,
    IncidentRequest,
    IncidentResponse,
    IngestRateRequest,
    IngestRateResponse,
    ListAiProjectsRequest,
    ListAiProjectsResponse,
    ListAiToolsRequest,
    ListAiToolsResponse,
    ListAppsRequest,
    ListAppsResponse,
    ListHostsResponse,
    ListSessionsRequest,
    ListSessionsResponse,
    ListSourceIpsRequest,
    ListSourceIpsResponse,
    LogEntry,
    PatternsRequest,
    PatternsResponse,
    ProjectContextRequest,
    ProjectContextResponse,
    SearchLogsRequest,
    SearchLogsResponse,
    SearchSessionsRequest,
    SearchSessionsResponse,
    SearchedSessionEntry,
    ServiceJournalEntry,
    SeverityCount,
    SimilarIncidentsRequest,
    SimilarIncidentsResponse,
    ServiceLogsRequest,
    ServiceLogsResponse,
    SilentHostsRequest,
    SilentHostsResponse,
    TailLogsRequest,
    TimelineRequest,
    TimelineResponse,
    UnackErrorRequest,
    UnackErrorResponse,
    UnaddressedErrorsRequest,
    UnaddressedErrorsResponse,
    UsageBlock,
    UsageBlocksRequest,
    UsageBlocksResponse,
};
pub use service::{run_service_logs, SyslogService};
pub use time::parse_optional_timestamp;

#[cfg(test)]
#[path = "app/mod_tests.rs"]
mod tests;
