mod correlate;
mod error;
pub(crate) mod error_detection;
pub(crate) mod heartbeat_flags;
pub(crate) mod incident_findings;
pub mod llm_runner;
mod models;
mod os_adapter;
mod services;
pub(crate) mod skill_incident_findings;
pub mod skill_signal_detectors;
pub(crate) mod time;
mod watch_status;

pub use correlate::severity_at_or_above;
pub use error::{ServiceError, ServiceResult};
pub use incident_findings::{ContributingFactor, FailureMode, IncidentFindings, PreventionHint};
pub use models::{
    AbuseIncident,
    AbuseMatch,
    AbuseSearchRequest,
    AbuseSearchResponse,
    // Error detection
    AckErrorRequest,
    AckErrorResponse,
    AiAssessEvidenceSummary,
    AiAssessRequest,
    AiAssessResponse,
    AiCheckpointsRequest,
    AiCorrelateLimitPolicy,
    AiCorrelateRequest,
    AiCorrelateResponse,
    AiCorrelationAnchor,
    AiIncidentRequest,
    AiIncidentResponse,
    AiInvestigateRequest,
    AiInvestigateResponse,
    AiLimitPolicy,
    AiParseErrorsRequest,
    AiProjectEntry,
    AiPruneCheckpointsRequest,
    AiSessionEntry,
    AiSkillIncidentRequest,
    AiSkillIncidentResponse,
    AiSkillInvestigateRequest,
    AiSkillInvestigateResponse,
    AiToolEntry,
    AiWatchStatusReport,
    AnomaliesRequest,
    AnomaliesResponse,
    AppEntitySummary,
    AppEvidenceSummary,
    AppGraphEntityResponse,
    AppGraphEvidenceResponse,
    AppGraphResponse,
    AppLogCount,
    AppLogSummary,
    AppRelationshipSummary,
    AskHistoryRequest,
    AskHistoryResponse,
    AskInvestigationRequest,
    AskInvestigationResponse,
    ClockSkewRequest,
    ClockSkewResponse,
    CompareRequest,
    CompareResponse,
    ContextRequest,
    ContextResponse,
    CorrelateEventsRequest,
    CorrelateEventsResponse,
    CorrelateStateRequest,
    CorrelateStateResponse,
    CorrelatedHost,
    CorrelatedSession,
    DbBackupRequest,
    DbBackupResult,
    DbCheckpointRequest,
    DbCheckpointResult,
    DbIntegrityJobStarted,
    DbIntegrityRequest,
    DbIntegrityResult,
    DbMaintenanceStatus,
    DbStats,
    DbVacuumRequest,
    DbVacuumResult,
    ErrorSignatureEntry,
    ErrorSummaryEntry,
    FileTailAddRequest,
    FileTailOp,
    FileTailRequest,
    FileTailResponse,
    FileTailSource,
    FileTailStatus,
    FilterLogsRequest,
    FleetStateRequest,
    FleetStateResponse,
    GetErrorsRequest,
    GetErrorsResponse,
    GetLogRequest,
    GetLogResponse,
    GraphAroundRequest,
    GraphAroundResponse,
    GraphEntity,
    GraphEntityCandidate,
    GraphEntityLookupRequest,
    GraphEntityLookupResponse,
    GraphEntitySummary,
    GraphEvidence,
    GraphEvidenceLookupRequest,
    GraphEvidenceLookupResponse,
    GraphExplainRequest,
    GraphExplainResponse,
    GraphIncidentNarrative,
    GraphNarrativeChain,
    GraphNextQuery,
    GraphProjectionStatusResponse,
    GraphRebuildResponse,
    GraphRebuildStatsResponse,
    GraphRelationship,
    GraphResponseMetadata,
    GraphSourceLogSummary,
    HomelabMapRequest,
    HomelabMapResponse,
    HostEntry,
    HostStateRequest,
    HostStateResponse,
    INVESTIGATION_UI_VERSION,
    IncidentCluster,
    IncidentContextRequest,
    IncidentContextResponse,
    IncidentEvent,
    IncidentEvidence,
    IncidentRequest,
    IncidentResponse,
    IngestRateRequest,
    IngestRateResponse,
    InvestigationBudget,
    InvestigationBudgetUsed,
    InvestigationClaim,
    InvestigationClaimType,
    InvestigationEnvelope,
    InvestigationMetadata,
    InvestigationVersionResponse,
    ListAiProjectsRequest,
    ListAiProjectsResponse,
    ListAiToolsRequest,
    ListAiToolsResponse,
    ListAppsRequest,
    ListAppsResponse,
    ListHostsResponse,
    ListSessionsRequest,
    ListSessionsResponse,
    ListSkillEventsRequest,
    ListSkillEventsResponse,
    ListSourceIpsRequest,
    ListSourceIpsResponse,
    LlmInvocationsRequest,
    LogEntry,
    MaintenanceJobStatus,
    NotificationsRecentRequest,
    PatternsRequest,
    PatternsResponse,
    ProjectContextRequest,
    ProjectContextResponse,
    RequestActor,
    SearchLogsRequest,
    SearchLogsResponse,
    SearchSessionsRequest,
    SearchSessionsResponse,
    SearchedSessionEntry,
    ServiceJournalEntry,
    ServiceLogsRequest,
    ServiceLogsResponse,
    SeverityCount,
    SilentHostsRequest,
    SilentHostsResponse,
    SimilarIncidentsRequest,
    SimilarIncidentsResponse,
    SkillBackfillRequest,
    SkillBackfillResult,
    SkillEventEntry,
    TailLogsRequest,
    TimelineRequest,
    TimelineResponse,
    TopicCorrelateRequest,
    TopicCorrelateResponse,
    UnackErrorRequest,
    UnackErrorResponse,
    UnaddressedErrorsRequest,
    UnaddressedErrorsResponse,
    UsageBlock,
    UsageBlocksRequest,
    UsageBlocksResponse,
    app_entity_summary,
    app_evidence_summary,
    app_graph_from_around_response,
    app_graph_from_explain_response,
    app_log_summary,
    app_relationship_summary,
    topology_findings,
};
pub use services::wal_checkpoint_complete;
// Transport-facing constants re-exported so surfaces (mcp/schemas.rs) never
// import db:: directly — app/ is the only db consumer (full-review AL1).
pub(crate) use crate::db::{PATTERN_SCAN_LIMIT_MAX, SEVERITY_LEVELS};
pub use os_adapter::SystemOsAdapter;
pub use services::{CortexService, run_compose_status, run_service_logs};
pub use time::{parse_optional_timestamp, parse_time_arg};

#[cfg(test)]
#[path = "app/mod_tests.rs"]
mod tests;
